class NceplibsG2 < Formula
  desc "Fortran library for encoding/decoding GRIB2 messages"
  homepage "https://github.com/NOAA-EMC/NCEPLIBS-g2"
  url "https://github.com/NOAA-EMC/NCEPLIBS-g2/archive/refs/tags/v4.0.0.tar.gz"
  sha256 "9559590b021ac0be462d975dddb92b0a1e368071aa6b13d59ce35dad8a4649fd"
  license :public_domain

  depends_on "cmake" => :build
  depends_on "gcc" => :build
  depends_on "pkg-config" => :build
  depends_on "jasper"
  depends_on "libpng"
  depends_on "nceplibs-bacio"
  depends_on "nceplibs-g2c"
  depends_on "nceplibs-ip"
  depends_on "nceplibs-w3emc"
  depends_on "openblas"

  def install
    gcc_formula = Formula["gcc"]

    gcc_bin = Dir["#{gcc_formula.opt_bin}/gcc-[0-9]*"]
                .select { |f| File.basename(f) =~ /\Agcc-\d+\z/ }
                .max
    gfortran_bin = Dir["#{gcc_formula.opt_bin}/gfortran-[0-9]*"]
                     .select { |f| File.basename(f) =~ /\Agfortran-\d+\z/ }
                     .max

    ENV["CC"] = gcc_bin
    ENV["FC"] = gfortran_bin

    ip_prefix = Formula["nceplibs-ip"].opt_prefix
    w3emc_prefix = Formula["nceplibs-w3emc"].opt_prefix
    openblas_prefix = Formula["openblas"].opt_prefix
    libpng_prefix = Formula["libpng"].opt_prefix

    prefix_paths = [
      openblas_prefix,
      w3emc_prefix,
      ip_prefix,
      libpng_prefix,
      Formula["nceplibs-bacio"].opt_prefix,
      Formula["nceplibs-g2c"].opt_prefix,
      Formula["jasper"].opt_prefix,
    ].join(";")

    include_paths = [
      "#{w3emc_prefix}/include_4",
      "#{w3emc_prefix}/include_d",
      "#{ip_prefix}/include_d",
      "#{ip_prefix}/include_4",
    ].join(";")

    args = std_cmake_args + [
      "-DCMAKE_PREFIX_PATH=#{prefix_paths}",
      "-DCMAKE_INCLUDE_PATH=#{include_paths}",
      "-DBLA_VENDOR=OpenBLAS",
      "-DBUILD_TESTING=OFF",
    ]

    # Build static libraries
    system "cmake", "-S", ".", "-B", "build_static", *args, "-DBUILD_SHARED_LIBS=OFF"
    system "cmake", "--build", "build_static"
    system "cmake", "--install", "build_static"

    # Build shared libraries
    system "cmake", "-S", ".", "-B", "build_shared", *args, "-DBUILD_SHARED_LIBS=ON"
    system "cmake", "--build", "build_shared"
    system "cmake", "--install", "build_shared"

    # Handle precision directories if generated by g2
    %w[include_4 include_d].each do |inc_dir|
      next unless (prefix/inc_dir).exist?

      (include/inc_dir).mkpath
      cp_r Dir[prefix/"#{inc_dir}/*"], include/inc_dir
      rm_r(prefix/inc_dir)
      (prefix/inc_dir).make_symlink(include/inc_dir)
    end
  end

  test do
    system "false"
  end
end
